@extends('layouts.admin')

@section('title', 'Project')

@section('content')
    <header class="content-index-header"><div><span class="eyebrow">Portfolio library</span><h1>Project</h1><p>Susun karya, teknologi, tautan demo, dan studi kasus lengkap.</p></div><a class="button" href="{{ route('admin.projects.create') }}"> Tambah project</a></header>
    <form class="content-filters" method="get"><label><span class="sr-only">Cari project</span><input name="q" value="{{ request('q') }}" placeholder=" Cari nama project…"></label><label><span class="sr-only">Filter status</span><select name="status"><option value="">Semua status</option>@foreach (App\Enums\ContentStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status') === $status->value)>{{ ucfirst($status->value) }}</option>@endforeach</select></label><button type="submit">Terapkan filter</button>@if(request()->hasAny(['q','status']))<a href="{{ route('admin.projects.index') }}">Reset</a>@endif</form>
    <div class="table-wrap"><table><thead><tr><th>Project</th><th>Status</th><th>Tahun</th><th>Kategori</th><th>Diperbarui</th><th><span class="sr-only">Aksi</span></th></tr></thead><tbody>@forelse ($projects as $project)<tr><td><strong>{{ $project->name }}</strong><small class="table-subtitle">{{ $project->is_featured ? ' Unggulan' : '/'.$project->slug }}</small></td><td><span class="status-badge {{ $project->status->value }}">{{ ucfirst($project->status->value) }}</span></td><td>{{ $project->year }}</td><td>{{ $project->category?->name ?? '—' }}</td><td>{{ $project->updated_at->diffForHumans() }}</td><td class="table-actions"><a href="{{ route('admin.projects.preview', $project) }}" target="_blank" title="Preview"></a><a href="{{ route('admin.projects.edit', $project) }}">Edit</a><form method="post" action="{{ route('admin.projects.destroy', $project) }}" onsubmit="return confirm('Hapus project ini?')">@csrf @method('delete')<button>Hapus</button></form></td></tr>@empty<tr><td colspan="6"><div class="empty">Belum ada project sesuai filter.</div></td></tr>@endforelse</tbody></table></div>
    {{ $projects->links() }}
@endsection
