@extends('layouts.admin')

@section('title', 'Tulisan')

@section('content')
    <header class="content-index-header"><div><span class="eyebrow">Content library</span><h1>Tulisan</h1><p>Kelola draft, jadwal, dan artikel yang sudah tampil di website.</p></div><a class="button" href="{{ route('admin.posts.create') }}"> Tulis artikel</a></header>
    <form class="content-filters" method="get"><label><span class="sr-only">Cari tulisan</span><input name="q" value="{{ request('q') }}" placeholder=" Cari judul tulisan…"></label><label><span class="sr-only">Filter status</span><select name="status"><option value="">Semua status</option>@foreach (App\Enums\ContentStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status') === $status->value)>{{ ucfirst($status->value) }}</option>@endforeach</select></label><button type="submit">Terapkan filter</button>@if(request()->hasAny(['q','status']))<a href="{{ route('admin.posts.index') }}">Reset</a>@endif</form>
    <div class="table-wrap"><table><thead><tr><th>Judul</th><th>Status</th><th>Publikasi</th><th>Diperbarui</th><th><span class="sr-only">Aksi</span></th></tr></thead><tbody>@forelse ($posts as $post)<tr><td><strong>{{ $post->title }}</strong><small class="table-subtitle">/{{ $post->slug }}</small></td><td><span class="status-badge {{ $post->status->value }}">{{ ucfirst($post->status->value) }}</span></td><td>{{ $post->published_at?->translatedFormat('d M Y H:i') ?? '—' }}</td><td>{{ $post->updated_at->diffForHumans() }}</td><td class="table-actions"><a href="{{ route('admin.posts.preview', $post) }}" target="_blank" title="Preview"></a><a href="{{ route('admin.posts.edit', $post) }}">Edit</a><form method="post" action="{{ route('admin.posts.destroy', $post) }}" onsubmit="return confirm('Hapus tulisan ini?')">@csrf @method('delete')<button>Hapus</button></form></td></tr>@empty<tr><td colspan="5"><div class="empty">Belum ada tulisan sesuai filter.</div></td></tr>@endforelse</tbody></table></div>
    {{ $posts->links() }}
@endsection
